### ISSUE TITLE
About update_lr and meta_lr

### ISSUE THREAD

**Issue by luyao777** [foolyc/Meta-SGD#1]
hi,foolyc.
I have read your Meta-SGD code recently, that's a good project.
But I have some questions about the code and paper.
In the paper, update_lr and meta_lr seem like same item, and used element wise product with network parameters.
The line here seems not conform to the paper?
And set self.meta_lr and self.update same tf.variable?
https://github.com/foolyc/Meta-SGD/blob/4922a8dab9bf6368654f174b9d3976dc77627012/maml.py#L64

**Comment by foolyc** [comment]
@luyao777 
meta_lr is the meta learning rate for meta update.(outer update).
update_lr stands for the task learning rate for each task(inner update), which can be updated by the meta update(outer update)(this is the the key idea of meta-SGD).
<img width="795" alt="2071" src="https://user-images.githubusercontent.com/7566074/39340243-99ec2486-49ff-11e8-93ef-34fd70fa621f.png">
